name: facial_recognition
channels:
    - conda-forge
    - defaults

dependencies:
    - python=3.8
    - pip
    # Core specific python
    - numpy
    - pandas
    - matplotlib
    # Jupyter environment
    - notebook
    - jupyter_contrib_nbextensions
    # Machine Learning
    - scikit-learn
    - scipy
    # Deep learning
    - tensorflow=2.6.0
    # Computer Vision
    - opencv-python
